language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

before_script:
  - npm install
script:
  - npm run build
  - npm run test

deploy:
  provider: s3
  access_key_id: AKIAIWLZ5FFXLLJ4OZYQ
  secret_access_key:
    secure: X5u1zdwxelIMaiKQZwxPBJzea2c2o6etDFWg31jME9BWNpU+k7O0n8AKGeq3oljgZGFp6oXyJVVxw9vo3HKiCaGXF2Tqso4unqpaMewlhEGGA2rhO3hSE3Tyeom10xJB2mLHy6MUVZG9DqIzFomRyU53pZ2nHSgCmjw3XVM1gmNWgnew90EA/9Dx2S4DuWVYZPVQoNDIMKeaA3dmpJrIVNVwhTYe8W7xY9v34/RHxZRt6qCwyEk/v9aTArFWPGvAEyOCQ+3ci7817Sd9eZhdV49W+jSWfGm5xiZ9G/77n8IEh9So68Oi7O2YgFDw4KgMxCbyDtJvE1qzpAQjxJf8Ho8t7VJq8u23WxQq5EC50v1Oi7VCn6KF6E8pKuKg8vhEXKbvy3T19KOMZmWzCCSUB7gT0xpVy9u9+H6O01ZD7YRcuUe819OZn6P1qQfWGn84brjETAMXzWGFWG82YB/P8uidsVcM1R7Sk5Q0J9a6yXF/GEdJDhMxvy1VYljRjT88QRPd9kPLA9MGwpiEFWQ8hqkkHS1GUmyGFp6gBk5VeU2AK+JXX06SBTo/3CXcHocwHwTQpXiJa8mPEMfRReIuNUYq/twSAVH5c+1lHOqvOtT5Th4egSSRCt5nBCOAIz00Yjlayu2CJ596QPtgUiLhoibWBOE7f5lhwQ+QayGG2JA=
  bucket: music-genre-generator
  acl: public-read
  on:
    repo: ryanjackman/genre-generator
  local_dir: dist
  skip_cleanup: true
