language: node_js
node_js:
  - "node"

deploy:
  provider: s3
  access_key_id: AKIAJGGJL5C6JHUBSMZA
  secret_access_key:
    secure: GEQ0IPuP6VrtipotdDBF4S675ujgpV9iuWcHXn/1qB5fidy53QBNISgWePKpuQpC1XT4I87e0oadJA4shrM6W4O1QVAgdSxa1AUOasF5T+iMniFLLBccsDJtkiAgv0Bex+84ZPoC+Kd7iFnL7UkC69E3QVm/jf2fWxgGO3G61lcj0XLKSY1jwc2K8tPO5uc2+MESajodYZy9a7fVABXCXUesa8lE2lILPxS2XH1VkV3mH+86XGKHBV+aWbXk9/iT5gqWOlel2uNpoMGPT+XXiWLmgCYo3zmMxJ4e467+jqwtlq0p3Dy3q7gFH5R158TBkdsLrLUK80hBHZA8rbdBOK3OGnyg8Ie96NxYSKrW4IN2pBiapfKYCzax+z9sWcYRBnw57qzO+7XYj4cf4/3rVJ7gSqRL6LMbXziQmwXI29z3h+KsnhQIm+u3agGijvLeAfhU8Cs0kK8xWpAMzxun9aAQo0fPoo8zRYUvi2aXW+fUF2yrnuVr8a/dbqQBXAaqvhjD81zn17L1YT155PHbAkq4iBDIynIuDU+FellxoZOr+Eq+y2nGA+QdYpEciznJ/rwVHwuU533XFe32m1/JsbXFpyTd8I4ilT9mrK6kdzJ3vrFHFLvBJtzCDoPvxutI4Q1M3C9yxLkvzxpmzZ+phehQSIW5PKOZKAAHDnZuCVc=
  bucket: music-genre-generator
